// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/presentation/bloc/export_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cherry_note/features/sync/domain/services/export_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExportResult_0 extends _i1.SmartFake implements _i2.ExportResult {
  _FakeExportResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportService extends _i1.Mock implements _i2.ExportService {
  MockExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isExporting => (super.noSuchMethod(
        Invocation.getter(#isExporting),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i2.ExportResult> exportToFolder(
    String? localPath, {
    _i2.ExportOptions? options,
    _i3.StreamController<_i2.ExportProgress>? progressController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToFolder,
          [localPath],
          {
            #options: options,
            #progressController: progressController,
          },
        ),
        returnValue: _i3.Future<_i2.ExportResult>.value(_FakeExportResult_0(
          this,
          Invocation.method(
            #exportToFolder,
            [localPath],
            {
              #options: options,
              #progressController: progressController,
            },
          ),
        )),
      ) as _i3.Future<_i2.ExportResult>);

  @override
  _i3.Future<_i2.ExportResult> exportToZip(
    String? zipPath, {
    _i2.ExportOptions? options,
    _i3.StreamController<_i2.ExportProgress>? progressController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToZip,
          [zipPath],
          {
            #options: options,
            #progressController: progressController,
          },
        ),
        returnValue: _i3.Future<_i2.ExportResult>.value(_FakeExportResult_0(
          this,
          Invocation.method(
            #exportToZip,
            [zipPath],
            {
              #options: options,
              #progressController: progressController,
            },
          ),
        )),
      ) as _i3.Future<_i2.ExportResult>);

  @override
  _i3.Future<_i2.ExportResult> exportFolder(
    String? folderPath,
    String? localPath, {
    bool? includeMetadata = true,
    _i3.StreamController<_i2.ExportProgress>? progressController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFolder,
          [
            folderPath,
            localPath,
          ],
          {
            #includeMetadata: includeMetadata,
            #progressController: progressController,
          },
        ),
        returnValue: _i3.Future<_i2.ExportResult>.value(_FakeExportResult_0(
          this,
          Invocation.method(
            #exportFolder,
            [
              folderPath,
              localPath,
            ],
            {
              #includeMetadata: includeMetadata,
              #progressController: progressController,
            },
          ),
        )),
      ) as _i3.Future<_i2.ExportResult>);

  @override
  _i3.Future<void> cancelExport() => (super.noSuchMethod(
        Invocation.method(
          #cancelExport,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
