// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/presentation/bloc/import_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cherry_note/features/sync/domain/services/import_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImportResult_0 extends _i1.SmartFake implements _i2.ImportResult {
  _FakeImportResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValidationResult_1 extends _i1.SmartFake
    implements _i2.ValidationResult {
  _FakeValidationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportService extends _i1.Mock implements _i2.ImportService {
  MockImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isImporting => (super.noSuchMethod(
        Invocation.getter(#isImporting),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i2.ImportResult> importFromFolder(
    String? localPath, {
    _i2.ImportOptions? options,
    _i3.StreamController<_i2.ImportProgress>? progressController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromFolder,
          [localPath],
          {
            #options: options,
            #progressController: progressController,
          },
        ),
        returnValue: _i3.Future<_i2.ImportResult>.value(_FakeImportResult_0(
          this,
          Invocation.method(
            #importFromFolder,
            [localPath],
            {
              #options: options,
              #progressController: progressController,
            },
          ),
        )),
      ) as _i3.Future<_i2.ImportResult>);

  @override
  _i3.Future<_i2.ImportResult> importFromZip(
    String? zipPath, {
    _i2.ImportOptions? options,
    _i3.StreamController<_i2.ImportProgress>? progressController,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromZip,
          [zipPath],
          {
            #options: options,
            #progressController: progressController,
          },
        ),
        returnValue: _i3.Future<_i2.ImportResult>.value(_FakeImportResult_0(
          this,
          Invocation.method(
            #importFromZip,
            [zipPath],
            {
              #options: options,
              #progressController: progressController,
            },
          ),
        )),
      ) as _i3.Future<_i2.ImportResult>);

  @override
  _i3.Future<_i2.ValidationResult> validateImportStructure(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateImportStructure,
          [path],
        ),
        returnValue:
            _i3.Future<_i2.ValidationResult>.value(_FakeValidationResult_1(
          this,
          Invocation.method(
            #validateImportStructure,
            [path],
          ),
        )),
      ) as _i3.Future<_i2.ValidationResult>);

  @override
  _i3.Future<void> resolveConflict(
    String? filePath,
    _i2.ConflictStrategy? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            filePath,
            strategy,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.FileConflict>> getPendingConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingConflicts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i2.FileConflict>>.value(<_i2.FileConflict>[]),
      ) as _i3.Future<List<_i2.FileConflict>>);

  @override
  _i3.Future<void> cancelImport() => (super.noSuchMethod(
        Invocation.method(
          #cancelImport,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
