// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/presentation/bloc/sync_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cherry_note/features/sync/domain/services/auto_sync_service.dart'
    as _i3;
import 'package:cherry_note/features/sync/domain/services/sync_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncInfo_1 extends _i1.SmartFake implements _i2.SyncInfo {
  _FakeSyncInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoSyncConfig_2 extends _i1.SmartFake
    implements _i3.AutoSyncConfig {
  _FakeAutoSyncConfig_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoSyncStats_3 extends _i1.SmartFake implements _i3.AutoSyncStats {
  _FakeAutoSyncStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAutoSyncEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoSyncEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.SyncStatus> get syncStatusStream => (super.noSuchMethod(
        Invocation.getter(#syncStatusStream),
        returnValue: _i4.Stream<_i2.SyncStatus>.empty(),
      ) as _i4.Stream<_i2.SyncStatus>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncPaused => (super.noSuchMethod(
        Invocation.getter(#isSyncPaused),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> enableAutoSync(
          {Duration? interval = const Duration(minutes: 5)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoSync,
          [],
          {#interval: interval},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disableAutoSync() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncResult> syncToRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncToRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncToRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncFromRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFromRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> fullSync() => (super.noSuchMethod(
        Invocation.method(
          #fullSync,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #fullSync,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncFile(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #syncFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> uploadFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #uploadFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> downloadFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #downloadFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> deleteFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #deleteFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<void> handleConflict(
    String? filePath,
    _i2.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleConflict,
          [
            filePath,
            resolution,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.FileConflict>> getConflicts() => (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.FileConflict>>.value(<_i2.FileConflict>[]),
      ) as _i4.Future<List<_i2.FileConflict>>);

  @override
  _i4.Future<void> clearConflicts() => (super.noSuchMethod(
        Invocation.method(
          #clearConflicts,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncInfo> getSyncInfo() => (super.noSuchMethod(
        Invocation.method(
          #getSyncInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncInfo>.value(_FakeSyncInfo_1(
          this,
          Invocation.method(
            #getSyncInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncInfo>);

  @override
  _i4.Future<void> updateSyncInfo(_i2.SyncInfo? info) => (super.noSuchMethod(
        Invocation.method(
          #updateSyncInfo,
          [info],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getModifiedFiles() => (super.noSuchMethod(
        Invocation.method(
          #getModifiedFiles,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getLocalChanges() => (super.noSuchMethod(
        Invocation.method(
          #getLocalChanges,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getRemoteChanges() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteChanges,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> hasLocalChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasLocalChanges,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasRemoteChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasRemoteChanges,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLocalFileTimestamp(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalFileTimestamp,
          [filePath],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<DateTime?> getRemoteFileTimestamp(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteFileTimestamp,
          [filePath],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<bool> isLocalFileNewer(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #isLocalFileNewer,
          [filePath],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isRemoteFileNewer(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #isRemoteFileNewer,
          [filePath],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> pauseSync() => (super.noSuchMethod(
        Invocation.method(
          #pauseSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resumeSync() => (super.noSuchMethod(
        Invocation.method(
          #resumeSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetSync() => (super.noSuchMethod(
        Invocation.method(
          #resetSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AutoSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoSyncService extends _i1.Mock implements _i3.AutoSyncService {
  MockAutoSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AutoSyncState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i3.AutoSyncState.disabled,
      ) as _i3.AutoSyncState);

  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i3.AutoSyncEvent> get eventStream => (super.noSuchMethod(
        Invocation.getter(#eventStream),
        returnValue: _i4.Stream<_i3.AutoSyncEvent>.empty(),
      ) as _i4.Stream<_i3.AutoSyncEvent>);

  @override
  _i4.Stream<_i3.AutoSyncState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i4.Stream<_i3.AutoSyncState>.empty(),
      ) as _i4.Stream<_i3.AutoSyncState>);

  @override
  _i4.Future<void> configure(_i3.AutoSyncConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #configure,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.AutoSyncConfig> getConfig() => (super.noSuchMethod(
        Invocation.method(
          #getConfig,
          [],
        ),
        returnValue: _i4.Future<_i3.AutoSyncConfig>.value(_FakeAutoSyncConfig_2(
          this,
          Invocation.method(
            #getConfig,
            [],
          ),
        )),
      ) as _i4.Future<_i3.AutoSyncConfig>);

  @override
  _i4.Future<void> enable() => (super.noSuchMethod(
        Invocation.method(
          #enable,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disable() => (super.noSuchMethod(
        Invocation.method(
          #disable,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> triggerSync({String? reason}) => (super.noSuchMethod(
        Invocation.method(
          #triggerSync,
          [],
          {#reason: reason},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> triggerFileSync(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #triggerFileSync,
          [filePath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onFileCreated(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #onFileCreated,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onFileModified(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #onFileModified,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onFileDeleted(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #onFileDeleted,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> onAppStart() => (super.noSuchMethod(
        Invocation.method(
          #onAppStart,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> onAppResume() => (super.noSuchMethod(
        Invocation.method(
          #onAppResume,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> onAppPause() => (super.noSuchMethod(
        Invocation.method(
          #onAppPause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.AutoSyncStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _i4.Future<_i3.AutoSyncStats>.value(_FakeAutoSyncStats_3(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i4.Future<_i3.AutoSyncStats>);

  @override
  _i4.Future<void> resetStats() => (super.noSuchMethod(
        Invocation.method(
          #resetStats,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
