// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/tags/presentation/widgets/tag_input_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cherry_note/features/tags/domain/entities/tag_filter.dart'
    as _i2;
import 'package:cherry_note/features/tags/presentation/bloc/tags_bloc.dart'
    as _i4;
import 'package:cherry_note/features/tags/presentation/bloc/tags_event.dart'
    as _i6;
import 'package:cherry_note/features/tags/presentation/bloc/tags_state.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTagFilter_0 extends _i1.SmartFake implements _i2.TagFilter {
  _FakeTagFilter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTagsState_1 extends _i1.SmartFake implements _i3.TagsState {
  _FakeTagsState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TagsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagsBloc extends _i1.Mock implements _i4.TagsBloc {
  MockTagsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TagFilter get currentFilter => (super.noSuchMethod(
        Invocation.getter(#currentFilter),
        returnValue: _FakeTagFilter_0(
          this,
          Invocation.getter(#currentFilter),
        ),
      ) as _i2.TagFilter);

  @override
  int get selectedTagCount => (super.noSuchMethod(
        Invocation.getter(#selectedTagCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasActiveFilter => (super.noSuchMethod(
        Invocation.getter(#hasActiveFilter),
        returnValue: false,
      ) as bool);

  @override
  _i3.TagsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTagsState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.TagsState);

  @override
  _i5.Stream<_i3.TagsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.TagsState>.empty(),
      ) as _i5.Stream<_i3.TagsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool isTagSelectedForFilter(String? tagName) => (super.noSuchMethod(
        Invocation.method(
          #isTagSelectedForFilter,
          [tagName],
        ),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.TagsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.TagsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.TagsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.TagsEvent>(
    _i7.EventHandler<E, _i3.TagsState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(_i7.Transition<_i6.TagsEvent, _i3.TagsState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.TagsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
