// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/domain/services/conflict_detection_service_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cherry_note/features/sync/domain/entities/batch_operation_result.dart'
    as _i2;
import 'package:cherry_note/features/sync/domain/entities/cancellation_token.dart'
    as _i7;
import 'package:cherry_note/features/sync/domain/entities/s3_config.dart'
    as _i5;
import 'package:cherry_note/features/sync/domain/repositories/s3_storage_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatchOperationResult_0 extends _i1.SmartFake
    implements _i2.BatchOperationResult {
  _FakeBatchOperationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [S3StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockS3StorageRepository extends _i1.Mock
    implements _i3.S3StorageRepository {
  MockS3StorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize(_i5.S3Config? config) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> uploadFile(
    String? key,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            key,
            content,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> downloadFile(String? key) => (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [key],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #downloadFile,
            [key],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteFile(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> fileExists(String? key) => (super.noSuchMethod(
        Invocation.method(
          #fileExists,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> listFiles(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #listFiles,
          [prefix],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> listFolders(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #listFolders,
          [prefix],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> createFolder(String? folderPath) => (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [folderPath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFolder(String? folderPath) => (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [folderPath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uploadMultipleFiles(Map<String, String>? files) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMultipleFiles,
          [files],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String>> downloadMultipleFiles(List<String>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadMultipleFiles,
          [keys],
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<_i2.BatchOperationResult> uploadMultipleFilesWithProgress(
    Map<String, String>? files, {
    void Function(_i2.BatchOperationProgress)? onProgress,
    _i7.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMultipleFilesWithProgress,
          [files],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i4.Future<_i2.BatchOperationResult>.value(
            _FakeBatchOperationResult_0(
          this,
          Invocation.method(
            #uploadMultipleFilesWithProgress,
            [files],
            {
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.BatchOperationResult>);

  @override
  _i4.Future<_i2.BatchOperationResult> downloadMultipleFilesWithProgress(
    List<String>? keys, {
    void Function(_i2.BatchOperationProgress)? onProgress,
    _i7.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadMultipleFilesWithProgress,
          [keys],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i4.Future<_i2.BatchOperationResult>.value(
            _FakeBatchOperationResult_0(
          this,
          Invocation.method(
            #downloadMultipleFilesWithProgress,
            [keys],
            {
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.BatchOperationResult>);

  @override
  _i4.Future<_i2.BatchOperationResult> deleteMultipleFilesWithProgress(
    List<String>? keys, {
    void Function(_i2.BatchOperationProgress)? onProgress,
    _i7.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMultipleFilesWithProgress,
          [keys],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i4.Future<_i2.BatchOperationResult>.value(
            _FakeBatchOperationResult_0(
          this,
          Invocation.method(
            #deleteMultipleFilesWithProgress,
            [keys],
            {
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.BatchOperationResult>);

  @override
  _i4.Future<_i2.BatchOperationResult> uploadFolderRecursively(
    String? folderPath,
    Map<String, String>? files, {
    void Function(_i2.BatchOperationProgress)? onProgress,
    _i7.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFolderRecursively,
          [
            folderPath,
            files,
          ],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i4.Future<_i2.BatchOperationResult>.value(
            _FakeBatchOperationResult_0(
          this,
          Invocation.method(
            #uploadFolderRecursively,
            [
              folderPath,
              files,
            ],
            {
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.BatchOperationResult>);

  @override
  _i4.Future<_i2.BatchOperationResult> downloadFolderRecursively(
    String? folderPath, {
    void Function(_i2.BatchOperationProgress)? onProgress,
    _i7.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFolderRecursively,
          [folderPath],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i4.Future<_i2.BatchOperationResult>.value(
            _FakeBatchOperationResult_0(
          this,
          Invocation.method(
            #downloadFolderRecursively,
            [folderPath],
            {
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.BatchOperationResult>);

  @override
  _i4.Future<_i2.BatchOperationResult> deleteFolderRecursively(
    String? folderPath, {
    void Function(_i2.BatchOperationProgress)? onProgress,
    _i7.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolderRecursively,
          [folderPath],
          {
            #onProgress: onProgress,
            #cancellationToken: cancellationToken,
          },
        ),
        returnValue: _i4.Future<_i2.BatchOperationResult>.value(
            _FakeBatchOperationResult_0(
          this,
          Invocation.method(
            #deleteFolderRecursively,
            [folderPath],
            {
              #onProgress: onProgress,
              #cancellationToken: cancellationToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.BatchOperationResult>);

  @override
  _i4.Future<Map<String, dynamic>?> getFileMetadata(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileMetadata,
          [key],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int?> getFileSize(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [key],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<DateTime?> getLastModified(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getLastModified,
          [key],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> syncToRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncToRemote,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncFromRemote,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
