// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/domain/services/conflict_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cherry_note/features/sync/domain/services/conflict_detection_service.dart'
    as _i3;
import 'package:cherry_note/features/sync/domain/services/conflict_resolution_service.dart'
    as _i2;
import 'package:cherry_note/features/sync/domain/services/sync_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConflictResolutionResult_0 extends _i1.SmartFake
    implements _i2.ConflictResolutionResult {
  _FakeConflictResolutionResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchConflictResolutionResult_1 extends _i1.SmartFake
    implements _i2.BatchConflictResolutionResult {
  _FakeBatchConflictResolutionResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConflictDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConflictDetectionService extends _i1.Mock
    implements _i3.ConflictDetectionService {
  MockConflictDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.ConflictDetectionResult?> detectFileConflict(
          String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectFileConflict,
          [filePath],
        ),
        returnValue: _i4.Future<_i3.ConflictDetectionResult?>.value(),
      ) as _i4.Future<_i3.ConflictDetectionResult?>);

  @override
  _i4.Future<List<_i3.ConflictDetectionResult>> detectConflicts(
          List<String>? filePaths) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectConflicts,
          [filePaths],
        ),
        returnValue: _i4.Future<List<_i3.ConflictDetectionResult>>.value(
            <_i3.ConflictDetectionResult>[]),
      ) as _i4.Future<List<_i3.ConflictDetectionResult>>);

  @override
  _i4.Future<List<_i3.ConflictDetectionResult>> detectAllConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #detectAllConflicts,
          [],
        ),
        returnValue: _i4.Future<List<_i3.ConflictDetectionResult>>.value(
            <_i3.ConflictDetectionResult>[]),
      ) as _i4.Future<List<_i3.ConflictDetectionResult>>);

  @override
  _i3.ConflictSeverity analyzeConflictSeverity(_i5.FileConflict? conflict) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeConflictSeverity,
          [conflict],
        ),
        returnValue: _i3.ConflictSeverity.low,
      ) as _i3.ConflictSeverity);

  @override
  List<_i5.ConflictResolution> getSuggestedResolutions(
          _i3.ConflictDetectionResult? result) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestedResolutions,
          [result],
        ),
        returnValue: <_i5.ConflictResolution>[],
      ) as List<_i5.ConflictResolution>);

  @override
  _i5.ConflictResolution? getAutoResolution(
          _i3.ConflictDetectionResult? result) =>
      (super.noSuchMethod(Invocation.method(
        #getAutoResolution,
        [result],
      )) as _i5.ConflictResolution?);

  @override
  _i4.Future<String> previewResolution(
    _i5.FileConflict? conflict,
    _i5.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #previewResolution,
          [
            conflict,
            resolution,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #previewResolution,
            [
              conflict,
              resolution,
            ],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [ConflictResolutionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConflictResolutionService extends _i1.Mock
    implements _i2.ConflictResolutionService {
  MockConflictResolutionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ConflictResolutionResult> resolveConflict(
    _i5.FileConflict? conflict,
    _i5.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            conflict,
            resolution,
          ],
        ),
        returnValue: _i4.Future<_i2.ConflictResolutionResult>.value(
            _FakeConflictResolutionResult_0(
          this,
          Invocation.method(
            #resolveConflict,
            [
              conflict,
              resolution,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ConflictResolutionResult>);

  @override
  _i4.Future<_i2.BatchConflictResolutionResult> resolveConflicts(
    List<_i5.FileConflict>? conflicts,
    _i2.ConflictResolutionStrategy? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflicts,
          [
            conflicts,
            strategy,
          ],
        ),
        returnValue: _i4.Future<_i2.BatchConflictResolutionResult>.value(
            _FakeBatchConflictResolutionResult_1(
          this,
          Invocation.method(
            #resolveConflicts,
            [
              conflicts,
              strategy,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BatchConflictResolutionResult>);

  @override
  _i4.Future<_i2.BatchConflictResolutionResult> autoResolveConflicts(
          List<_i3.ConflictDetectionResult>? detectionResults) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoResolveConflicts,
          [detectionResults],
        ),
        returnValue: _i4.Future<_i2.BatchConflictResolutionResult>.value(
            _FakeBatchConflictResolutionResult_1(
          this,
          Invocation.method(
            #autoResolveConflicts,
            [detectionResults],
          ),
        )),
      ) as _i4.Future<_i2.BatchConflictResolutionResult>);

  @override
  _i4.Future<String> previewResolution(
    _i5.FileConflict? conflict,
    _i5.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #previewResolution,
          [
            conflict,
            resolution,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #previewResolution,
            [
              conflict,
              resolution,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> createBackup(
    String? filePath,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBackup,
          [
            filePath,
            content,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createBackup,
            [
              filePath,
              content,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> restoreBackup(
    String? backupPath,
    String? originalPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreBackup,
          [
            backupPath,
            originalPath,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupBackups({Duration? olderThan}) => (super.noSuchMethod(
        Invocation.method(
          #cleanupBackups,
          [],
          {#olderThan: olderThan},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
