// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/domain/services/sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cherry_note/features/sync/domain/entities/sync_operation.dart'
    as _i5;
import 'package:cherry_note/features/sync/domain/services/sync_queue_service.dart'
    as _i3;
import 'package:cherry_note/features/sync/domain/services/sync_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncInfo_1 extends _i1.SmartFake implements _i2.SyncInfo {
  _FakeSyncInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncQueueStats_2 extends _i1.SmartFake
    implements _i3.SyncQueueStats {
  _FakeSyncQueueStats_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAutoSyncEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoSyncEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.SyncStatus> get syncStatusStream => (super.noSuchMethod(
        Invocation.getter(#syncStatusStream),
        returnValue: _i4.Stream<_i2.SyncStatus>.empty(),
      ) as _i4.Stream<_i2.SyncStatus>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncPaused => (super.noSuchMethod(
        Invocation.getter(#isSyncPaused),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> enableAutoSync(
          {Duration? interval = const Duration(minutes: 5)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoSync,
          [],
          {#interval: interval},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disableAutoSync() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncResult> syncToRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncToRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncToRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncFromRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFromRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> fullSync() => (super.noSuchMethod(
        Invocation.method(
          #fullSync,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #fullSync,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncFile(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #syncFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> uploadFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #uploadFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> downloadFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #downloadFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> deleteFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [filePath],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #deleteFile,
            [filePath],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<void> handleConflict(
    String? filePath,
    _i2.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleConflict,
          [
            filePath,
            resolution,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.FileConflict>> getConflicts() => (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.FileConflict>>.value(<_i2.FileConflict>[]),
      ) as _i4.Future<List<_i2.FileConflict>>);

  @override
  _i4.Future<void> clearConflicts() => (super.noSuchMethod(
        Invocation.method(
          #clearConflicts,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncInfo> getSyncInfo() => (super.noSuchMethod(
        Invocation.method(
          #getSyncInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.SyncInfo>.value(_FakeSyncInfo_1(
          this,
          Invocation.method(
            #getSyncInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SyncInfo>);

  @override
  _i4.Future<void> updateSyncInfo(_i2.SyncInfo? info) => (super.noSuchMethod(
        Invocation.method(
          #updateSyncInfo,
          [info],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getModifiedFiles() => (super.noSuchMethod(
        Invocation.method(
          #getModifiedFiles,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getLocalChanges() => (super.noSuchMethod(
        Invocation.method(
          #getLocalChanges,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getRemoteChanges() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteChanges,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> hasLocalChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasLocalChanges,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasRemoteChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasRemoteChanges,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLocalFileTimestamp(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalFileTimestamp,
          [filePath],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<DateTime?> getRemoteFileTimestamp(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteFileTimestamp,
          [filePath],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<bool> isLocalFileNewer(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #isLocalFileNewer,
          [filePath],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isRemoteFileNewer(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #isRemoteFileNewer,
          [filePath],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> pauseSync() => (super.noSuchMethod(
        Invocation.method(
          #pauseSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resumeSync() => (super.noSuchMethod(
        Invocation.method(
          #resumeSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetSync() => (super.noSuchMethod(
        Invocation.method(
          #resetSync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SyncQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncQueueService extends _i1.Mock implements _i3.SyncQueueService {
  MockSyncQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.SyncQueueEvent> get queueEvents => (super.noSuchMethod(
        Invocation.getter(#queueEvents),
        returnValue: _i4.Stream<_i3.SyncQueueEvent>.empty(),
      ) as _i4.Stream<_i3.SyncQueueEvent>);

  @override
  _i4.Future<void> enqueue(_i5.SyncOperation? operation) => (super.noSuchMethod(
        Invocation.method(
          #enqueue,
          [operation],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enqueueAll(List<_i5.SyncOperation>? operations) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueAll,
          [operations],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.SyncOperation?> dequeue() => (super.noSuchMethod(
        Invocation.method(
          #dequeue,
          [],
        ),
        returnValue: _i4.Future<_i5.SyncOperation?>.value(),
      ) as _i4.Future<_i5.SyncOperation?>);

  @override
  _i4.Future<List<_i5.SyncOperation>> getPendingOperations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingOperations,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.SyncOperation>>.value(<_i5.SyncOperation>[]),
      ) as _i4.Future<List<_i5.SyncOperation>>);

  @override
  _i4.Future<List<_i5.SyncOperation>> getOperationsForFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperationsForFile,
          [filePath],
        ),
        returnValue:
            _i4.Future<List<_i5.SyncOperation>>.value(<_i5.SyncOperation>[]),
      ) as _i4.Future<List<_i5.SyncOperation>>);

  @override
  _i4.Future<void> updateOperation(_i5.SyncOperation? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOperation,
          [operation],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAsCompleted(String? operationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsCompleted,
          [operationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAsFailed(
    String? operationId,
    String? errorMessage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsFailed,
          [
            operationId,
            errorMessage,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelOperation(String? operationId) => (super.noSuchMethod(
        Invocation.method(
          #cancelOperation,
          [operationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeOperation(String? operationId) => (super.noSuchMethod(
        Invocation.method(
          #removeOperation,
          [operationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearQueue,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupCompletedOperations({Duration? olderThan}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupCompletedOperations,
          [],
          {#olderThan: olderThan},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.SyncQueueStats> getQueueStats() => (super.noSuchMethod(
        Invocation.method(
          #getQueueStats,
          [],
        ),
        returnValue: _i4.Future<_i3.SyncQueueStats>.value(_FakeSyncQueueStats_2(
          this,
          Invocation.method(
            #getQueueStats,
            [],
          ),
        )),
      ) as _i4.Future<_i3.SyncQueueStats>);

  @override
  _i4.Future<bool> hasPendingOperations() => (super.noSuchMethod(
        Invocation.method(
          #hasPendingOperations,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.SyncOperation>> getFailedOperations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFailedOperations,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.SyncOperation>>.value(<_i5.SyncOperation>[]),
      ) as _i4.Future<List<_i5.SyncOperation>>);

  @override
  _i4.Future<void> retryFailedOperations() => (super.noSuchMethod(
        Invocation.method(
          #retryFailedOperations,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
