// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/domain/services/sync_manager_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cherry_note/features/sync/domain/services/conflict_detection_service.dart'
    as _i6;
import 'package:cherry_note/features/sync/domain/services/conflict_manager.dart'
    as _i4;
import 'package:cherry_note/features/sync/domain/services/conflict_resolution_service.dart'
    as _i3;
import 'package:cherry_note/features/sync/domain/services/sync_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncInfo_1 extends _i1.SmartFake implements _i2.SyncInfo {
  _FakeSyncInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConflictResolutionResult_2 extends _i1.SmartFake
    implements _i3.ConflictResolutionResult {
  _FakeConflictResolutionResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchConflictResolutionResult_3 extends _i1.SmartFake
    implements _i3.BatchConflictResolutionResult {
  _FakeBatchConflictResolutionResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConflictManagerStats_4 extends _i1.SmartFake
    implements _i4.ConflictManagerStats {
  _FakeConflictManagerStats_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAutoSyncEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoSyncEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.SyncStatus> get syncStatusStream => (super.noSuchMethod(
        Invocation.getter(#syncStatusStream),
        returnValue: _i5.Stream<_i2.SyncStatus>.empty(),
      ) as _i5.Stream<_i2.SyncStatus>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isSyncPaused => (super.noSuchMethod(
        Invocation.getter(#isSyncPaused),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> enableAutoSync(
          {Duration? interval = const Duration(minutes: 5)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoSync,
          [],
          {#interval: interval},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disableAutoSync() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SyncResult> syncToRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncToRemote,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncToRemote,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> syncFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncFromRemote,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFromRemote,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> fullSync() => (super.noSuchMethod(
        Invocation.method(
          #fullSync,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #fullSync,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> syncFile(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #syncFile,
          [filePath],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFile,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> uploadFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [filePath],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #uploadFile,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> downloadFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [filePath],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #downloadFile,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> deleteFile(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [filePath],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #deleteFile,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<void> handleConflict(
    String? filePath,
    _i2.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleConflict,
          [
            filePath,
            resolution,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.FileConflict>> getConflicts() => (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.FileConflict>>.value(<_i2.FileConflict>[]),
      ) as _i5.Future<List<_i2.FileConflict>>);

  @override
  _i5.Future<void> clearConflicts() => (super.noSuchMethod(
        Invocation.method(
          #clearConflicts,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SyncInfo> getSyncInfo() => (super.noSuchMethod(
        Invocation.method(
          #getSyncInfo,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncInfo>.value(_FakeSyncInfo_1(
          this,
          Invocation.method(
            #getSyncInfo,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncInfo>);

  @override
  _i5.Future<void> updateSyncInfo(_i2.SyncInfo? info) => (super.noSuchMethod(
        Invocation.method(
          #updateSyncInfo,
          [info],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getModifiedFiles() => (super.noSuchMethod(
        Invocation.method(
          #getModifiedFiles,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<String>> getLocalChanges() => (super.noSuchMethod(
        Invocation.method(
          #getLocalChanges,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<String>> getRemoteChanges() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteChanges,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> hasLocalChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasLocalChanges,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasRemoteChanges() => (super.noSuchMethod(
        Invocation.method(
          #hasRemoteChanges,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<DateTime?> getLocalFileTimestamp(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalFileTimestamp,
          [filePath],
        ),
        returnValue: _i5.Future<DateTime?>.value(),
      ) as _i5.Future<DateTime?>);

  @override
  _i5.Future<DateTime?> getRemoteFileTimestamp(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemoteFileTimestamp,
          [filePath],
        ),
        returnValue: _i5.Future<DateTime?>.value(),
      ) as _i5.Future<DateTime?>);

  @override
  _i5.Future<bool> isLocalFileNewer(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #isLocalFileNewer,
          [filePath],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isRemoteFileNewer(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #isRemoteFileNewer,
          [filePath],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> pauseSync() => (super.noSuchMethod(
        Invocation.method(
          #pauseSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumeSync() => (super.noSuchMethod(
        Invocation.method(
          #resumeSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetSync() => (super.noSuchMethod(
        Invocation.method(
          #resetSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ConflictManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConflictManager extends _i1.Mock implements _i4.ConflictManager {
  MockConflictManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i4.ConflictManagerEvent> get eventStream => (super.noSuchMethod(
        Invocation.getter(#eventStream),
        returnValue: _i5.Stream<_i4.ConflictManagerEvent>.empty(),
      ) as _i5.Stream<_i4.ConflictManagerEvent>);

  @override
  bool get isAutoDetectionEnabled => (super.noSuchMethod(
        Invocation.getter(#isAutoDetectionEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> enableAutoDetection(
          {Duration? interval = const Duration(minutes: 10)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoDetection,
          [],
          {#interval: interval},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disableAutoDetection() => (super.noSuchMethod(
        Invocation.method(
          #disableAutoDetection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ConflictDetectionResult?> detectFileConflict(
          String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #detectFileConflict,
          [filePath],
        ),
        returnValue: _i5.Future<_i6.ConflictDetectionResult?>.value(),
      ) as _i5.Future<_i6.ConflictDetectionResult?>);

  @override
  _i5.Future<List<_i6.ConflictDetectionResult>> detectAllConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #detectAllConflicts,
          [],
        ),
        returnValue: _i5.Future<List<_i6.ConflictDetectionResult>>.value(
            <_i6.ConflictDetectionResult>[]),
      ) as _i5.Future<List<_i6.ConflictDetectionResult>>);

  @override
  _i5.Future<List<_i6.ConflictDetectionResult>> getCurrentConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentConflicts,
          [],
        ),
        returnValue: _i5.Future<List<_i6.ConflictDetectionResult>>.value(
            <_i6.ConflictDetectionResult>[]),
      ) as _i5.Future<List<_i6.ConflictDetectionResult>>);

  @override
  _i5.Future<_i3.ConflictResolutionResult> resolveConflict(
    _i2.FileConflict? conflict,
    _i2.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            conflict,
            resolution,
          ],
        ),
        returnValue: _i5.Future<_i3.ConflictResolutionResult>.value(
            _FakeConflictResolutionResult_2(
          this,
          Invocation.method(
            #resolveConflict,
            [
              conflict,
              resolution,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ConflictResolutionResult>);

  @override
  _i5.Future<_i3.BatchConflictResolutionResult> resolveConflicts(
    List<_i2.FileConflict>? conflicts,
    _i3.ConflictResolutionStrategy? strategy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflicts,
          [
            conflicts,
            strategy,
          ],
        ),
        returnValue: _i5.Future<_i3.BatchConflictResolutionResult>.value(
            _FakeBatchConflictResolutionResult_3(
          this,
          Invocation.method(
            #resolveConflicts,
            [
              conflicts,
              strategy,
            ],
          ),
        )),
      ) as _i5.Future<_i3.BatchConflictResolutionResult>);

  @override
  _i5.Future<_i3.BatchConflictResolutionResult> autoResolveConflicts() =>
      (super.noSuchMethod(
        Invocation.method(
          #autoResolveConflicts,
          [],
        ),
        returnValue: _i5.Future<_i3.BatchConflictResolutionResult>.value(
            _FakeBatchConflictResolutionResult_3(
          this,
          Invocation.method(
            #autoResolveConflicts,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BatchConflictResolutionResult>);

  @override
  _i5.Future<String> previewResolution(
    _i2.FileConflict? conflict,
    _i2.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #previewResolution,
          [
            conflict,
            resolution,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #previewResolution,
            [
              conflict,
              resolution,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createBackup(
    String? filePath,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBackup,
          [
            filePath,
            content,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createBackup,
            [
              filePath,
              content,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> restoreBackup(
    String? backupPath,
    String? originalPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreBackup,
          [
            backupPath,
            originalPath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupBackups({Duration? olderThan}) => (super.noSuchMethod(
        Invocation.method(
          #cleanupBackups,
          [],
          {#olderThan: olderThan},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i4.ConflictManagerStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _i5.Future<_i4.ConflictManagerStats>.value(
            _FakeConflictManagerStats_4(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i5.Future<_i4.ConflictManagerStats>);

  @override
  _i5.Future<void> resetStats() => (super.noSuchMethod(
        Invocation.method(
          #resetStats,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> exportConflictReport() => (super.noSuchMethod(
        Invocation.method(
          #exportConflictReport,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #exportConflictReport,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
