// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/sync/data/services/auto_sync_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cherry_note/features/sync/domain/services/sync_manager.dart'
    as _i4;
import 'package:cherry_note/features/sync/domain/services/sync_queue_service.dart'
    as _i3;
import 'package:cherry_note/features/sync/domain/services/sync_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncInfo_1 extends _i1.SmartFake implements _i2.SyncInfo {
  _FakeSyncInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncQueueStats_2 extends _i1.SmartFake
    implements _i3.SyncQueueStats {
  _FakeSyncQueueStats_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncManager extends _i1.Mock implements _i4.SyncManager {
  MockSyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.SyncStatus> get syncStatusStream => (super.noSuchMethod(
        Invocation.getter(#syncStatusStream),
        returnValue: _i5.Stream<_i2.SyncStatus>.empty(),
      ) as _i5.Stream<_i2.SyncStatus>);

  @override
  _i5.Stream<_i3.SyncQueueEvent> get queueEventStream => (super.noSuchMethod(
        Invocation.getter(#queueEventStream),
        returnValue: _i5.Stream<_i3.SyncQueueEvent>.empty(),
      ) as _i5.Stream<_i3.SyncQueueEvent>);

  @override
  _i5.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleFileUpload(
    String? filePath, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleFileUpload,
          [filePath],
          {#metadata: metadata},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleFileDownload(
    String? filePath, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleFileDownload,
          [filePath],
          {#metadata: metadata},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleFileDelete(
    String? filePath, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleFileDelete,
          [filePath],
          {#metadata: metadata},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SyncResult> syncFileNow(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncFileNow,
          [filePath],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncFileNow,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncResult> performFullSync() => (super.noSuchMethod(
        Invocation.method(
          #performFullSync,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #performFullSync,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncInfo> getSyncStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSyncStatus,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncInfo>.value(_FakeSyncInfo_1(
          this,
          Invocation.method(
            #getSyncStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncInfo>);

  @override
  _i5.Future<_i3.SyncQueueStats> getQueueStats() => (super.noSuchMethod(
        Invocation.method(
          #getQueueStats,
          [],
        ),
        returnValue: _i5.Future<_i3.SyncQueueStats>.value(_FakeSyncQueueStats_2(
          this,
          Invocation.method(
            #getQueueStats,
            [],
          ),
        )),
      ) as _i5.Future<_i3.SyncQueueStats>);

  @override
  _i5.Future<List<_i2.FileConflict>> getConflicts() => (super.noSuchMethod(
        Invocation.method(
          #getConflicts,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.FileConflict>>.value(<_i2.FileConflict>[]),
      ) as _i5.Future<List<_i2.FileConflict>>);

  @override
  _i5.Future<void> resolveConflict(
    String? filePath,
    _i2.ConflictResolution? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveConflict,
          [
            filePath,
            resolution,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pauseSync() => (super.noSuchMethod(
        Invocation.method(
          #pauseSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumeSync() => (super.noSuchMethod(
        Invocation.method(
          #resumeSync,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasPendingOperations() => (super.noSuchMethod(
        Invocation.method(
          #hasPendingOperations,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
