// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/settings/presentation/bloc/settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cherry_note/core/services/s3_connection_test_service.dart'
    as _i2;
import 'package:cherry_note/core/services/settings_service.dart' as _i4;
import 'package:cherry_note/features/settings/data/services/settings_import_export_service.dart'
    as _i3;
import 'package:cherry_note/features/sync/domain/entities/s3_config.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeS3ConnectionTestResult_0 extends _i1.SmartFake
    implements _i2.S3ConnectionTestResult {
  _FakeS3ConnectionTestResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsImportExportResult_1 extends _i1.SmartFake
    implements _i3.SettingsImportExportResult {
  _FakeSettingsImportExportResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i4.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.S3Config?> getS3Config() => (super.noSuchMethod(
        Invocation.method(
          #getS3Config,
          [],
        ),
        returnValue: _i5.Future<_i6.S3Config?>.value(),
      ) as _i5.Future<_i6.S3Config?>);

  @override
  _i5.Future<void> saveS3Config(_i6.S3Config? config) => (super.noSuchMethod(
        Invocation.method(
          #saveS3Config,
          [config],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearS3Config() => (super.noSuchMethod(
        Invocation.method(
          #clearS3Config,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getThemeMode,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setThemeMode(String? themeMode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [themeMode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<double> getFontSize() => (super.noSuchMethod(
        Invocation.method(
          #getFontSize,
          [],
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);

  @override
  _i5.Future<void> setFontSize(double? fontSize) => (super.noSuchMethod(
        Invocation.method(
          #setFontSize,
          [fontSize],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getShowLineNumbers() => (super.noSuchMethod(
        Invocation.method(
          #getShowLineNumbers,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setShowLineNumbers(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowLineNumbers,
          [show],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getWordWrap() => (super.noSuchMethod(
        Invocation.method(
          #getWordWrap,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setWordWrap(bool? wrap) => (super.noSuchMethod(
        Invocation.method(
          #setWordWrap,
          [wrap],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getAutoSave() => (super.noSuchMethod(
        Invocation.method(
          #getAutoSave,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setAutoSave(bool? autoSave) => (super.noSuchMethod(
        Invocation.method(
          #setAutoSave,
          [autoSave],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getAutoSaveInterval() => (super.noSuchMethod(
        Invocation.method(
          #getAutoSaveInterval,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> setAutoSaveInterval(int? interval) => (super.noSuchMethod(
        Invocation.method(
          #setAutoSaveInterval,
          [interval],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getAutoSync() => (super.noSuchMethod(
        Invocation.method(
          #getAutoSync,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setAutoSync(bool? autoSync) => (super.noSuchMethod(
        Invocation.method(
          #setAutoSync,
          [autoSync],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getSyncInterval() => (super.noSuchMethod(
        Invocation.method(
          #getSyncInterval,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> setSyncInterval(int? interval) => (super.noSuchMethod(
        Invocation.method(
          #setSyncInterval,
          [interval],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getSyncOnStartup() => (super.noSuchMethod(
        Invocation.method(
          #getSyncOnStartup,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setSyncOnStartup(bool? sync) => (super.noSuchMethod(
        Invocation.method(
          #setSyncOnStartup,
          [sync],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getSyncOnClose() => (super.noSuchMethod(
        Invocation.method(
          #getSyncOnClose,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setSyncOnClose(bool? sync) => (super.noSuchMethod(
        Invocation.method(
          #setSyncOnClose,
          [sync],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getShowToolbar() => (super.noSuchMethod(
        Invocation.method(
          #getShowToolbar,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setShowToolbar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowToolbar,
          [show],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getShowStatusBar() => (super.noSuchMethod(
        Invocation.method(
          #getShowStatusBar,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setShowStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowStatusBar,
          [show],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getCompactMode() => (super.noSuchMethod(
        Invocation.method(
          #getCompactMode,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setCompactMode(bool? compact) => (super.noSuchMethod(
        Invocation.method(
          #setCompactMode,
          [compact],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> exportSettings() => (super.noSuchMethod(
        Invocation.method(
          #exportSettings,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> importSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #importSettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSettings,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [S3ConnectionTestService].
///
/// See the documentation for Mockito's code generation for more information.
class MockS3ConnectionTestService extends _i1.Mock
    implements _i2.S3ConnectionTestService {
  MockS3ConnectionTestService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.S3ConnectionTestResult> testConnection(_i6.S3Config? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [config],
        ),
        returnValue: _i5.Future<_i2.S3ConnectionTestResult>.value(
            _FakeS3ConnectionTestResult_0(
          this,
          Invocation.method(
            #testConnection,
            [config],
          ),
        )),
      ) as _i5.Future<_i2.S3ConnectionTestResult>);

  @override
  _i5.Future<_i2.S3ConnectionTestResult> testBucketAccess(
          _i6.S3Config? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #testBucketAccess,
          [config],
        ),
        returnValue: _i5.Future<_i2.S3ConnectionTestResult>.value(
            _FakeS3ConnectionTestResult_0(
          this,
          Invocation.method(
            #testBucketAccess,
            [config],
          ),
        )),
      ) as _i5.Future<_i2.S3ConnectionTestResult>);

  @override
  _i5.Future<_i2.S3ConnectionTestResult> testWritePermissions(
          _i6.S3Config? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #testWritePermissions,
          [config],
        ),
        returnValue: _i5.Future<_i2.S3ConnectionTestResult>.value(
            _FakeS3ConnectionTestResult_0(
          this,
          Invocation.method(
            #testWritePermissions,
            [config],
          ),
        )),
      ) as _i5.Future<_i2.S3ConnectionTestResult>);
}

/// A class which mocks [SettingsImportExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsImportExportService extends _i1.Mock
    implements _i3.SettingsImportExportService {
  MockSettingsImportExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.SettingsImportExportResult> exportSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #exportSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.SettingsImportExportResult>.value(
            _FakeSettingsImportExportResult_1(
          this,
          Invocation.method(
            #exportSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.SettingsImportExportResult>);

  @override
  _i5.Future<_i3.SettingsImportExportResult> exportSettingsToFile(
          String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportSettingsToFile,
          [filePath],
        ),
        returnValue: _i5.Future<_i3.SettingsImportExportResult>.value(
            _FakeSettingsImportExportResult_1(
          this,
          Invocation.method(
            #exportSettingsToFile,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i3.SettingsImportExportResult>);

  @override
  _i5.Future<_i3.SettingsImportExportResult> importSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #importSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.SettingsImportExportResult>.value(
            _FakeSettingsImportExportResult_1(
          this,
          Invocation.method(
            #importSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.SettingsImportExportResult>);

  @override
  _i5.Future<_i3.SettingsImportExportResult> importSettingsFromFile(
          String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #importSettingsFromFile,
          [filePath],
        ),
        returnValue: _i5.Future<_i3.SettingsImportExportResult>.value(
            _FakeSettingsImportExportResult_1(
          this,
          Invocation.method(
            #importSettingsFromFile,
            [filePath],
          ),
        )),
      ) as _i5.Future<_i3.SettingsImportExportResult>);
}
