// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/tags/presentation/bloc/tags_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cherry_note/features/tags/domain/entities/tag.dart' as _i2;
import 'package:cherry_note/features/tags/domain/repositories/tag_repository.dart'
    as _i3;
import 'package:cherry_note/features/tags/domain/usecases/create_tag.dart'
    as _i6;
import 'package:cherry_note/features/tags/domain/usecases/delete_tag.dart'
    as _i9;
import 'package:cherry_note/features/tags/domain/usecases/get_all_tags.dart'
    as _i5;
import 'package:cherry_note/features/tags/domain/usecases/get_tag_suggestions.dart'
    as _i8;
import 'package:cherry_note/features/tags/domain/usecases/search_tags.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTag_0 extends _i1.SmartFake implements _i2.Tag {
  _FakeTag_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTagStats_1 extends _i1.SmartFake implements _i3.TagStats {
  _FakeTagStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagRepository extends _i1.Mock implements _i3.TagRepository {
  MockTagRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Tag>> getAllTags() => (super.noSuchMethod(
        Invocation.method(
          #getAllTags,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
      ) as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<_i2.Tag?> getTagByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getTagByName,
          [name],
        ),
        returnValue: _i4.Future<_i2.Tag?>.value(),
      ) as _i4.Future<_i2.Tag?>);

  @override
  _i4.Future<_i2.Tag> createTag({
    required String? name,
    String? color,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTag,
          [],
          {
            #name: name,
            #color: color,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i2.Tag>.value(_FakeTag_0(
          this,
          Invocation.method(
            #createTag,
            [],
            {
              #name: name,
              #color: color,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i2.Tag>);

  @override
  _i4.Future<_i2.Tag> updateTag(_i2.Tag? tag) => (super.noSuchMethod(
        Invocation.method(
          #updateTag,
          [tag],
        ),
        returnValue: _i4.Future<_i2.Tag>.value(_FakeTag_0(
          this,
          Invocation.method(
            #updateTag,
            [tag],
          ),
        )),
      ) as _i4.Future<_i2.Tag>);

  @override
  _i4.Future<void> deleteTag(String? name) => (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTags(List<String>? names) => (super.noSuchMethod(
        Invocation.method(
          #deleteTags,
          [names],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Tag>> searchTags({
    required String? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTags,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
      ) as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<List<String>> getTagSuggestions({
    required String? query,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTagSuggestions,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i2.Tag>> getMostUsedTags({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostUsedTags,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
      ) as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<List<_i2.Tag>> getRecentlyUsedTags({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyUsedTags,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
      ) as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<void> updateTagUsage(String? tagName) => (super.noSuchMethod(
        Invocation.method(
          #updateTagUsage,
          [tagName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTagsUsage(List<String>? tagNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTagsUsage,
          [tagNames],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> cleanupUnusedTags() => (super.noSuchMethod(
        Invocation.method(
          #cleanupUnusedTags,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<_i3.TagStats> getTagStats() => (super.noSuchMethod(
        Invocation.method(
          #getTagStats,
          [],
        ),
        returnValue: _i4.Future<_i3.TagStats>.value(_FakeTagStats_1(
          this,
          Invocation.method(
            #getTagStats,
            [],
          ),
        )),
      ) as _i4.Future<_i3.TagStats>);

  @override
  bool isValidTagName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isValidTagName,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<bool> tagExists(String? name) => (super.noSuchMethod(
        Invocation.method(
          #tagExists,
          [name],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> syncTags() => (super.noSuchMethod(
        Invocation.method(
          #syncTags,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetAllTags].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllTags extends _i1.Mock implements _i5.GetAllTags {
  MockGetAllTags() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Tag>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
      ) as _i4.Future<List<_i2.Tag>>);
}

/// A class which mocks [CreateTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTag extends _i1.Mock implements _i6.CreateTag {
  MockCreateTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Tag> call(_i6.CreateTagParams? params) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Tag>.value(_FakeTag_0(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Tag>);
}

/// A class which mocks [SearchTags].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTags extends _i1.Mock implements _i7.SearchTags {
  MockSearchTags() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Tag>> call(_i7.SearchTagsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
      ) as _i4.Future<List<_i2.Tag>>);
}

/// A class which mocks [GetTagSuggestions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTagSuggestions extends _i1.Mock implements _i8.GetTagSuggestions {
  MockGetTagSuggestions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> call(_i8.GetTagSuggestionsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}

/// A class which mocks [DeleteTag].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTag extends _i1.Mock implements _i9.DeleteTag {
  MockDeleteTag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(_i9.DeleteTagParams? params) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
