// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/main/presentation/pages/main_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cherry_note/features/folders/presentation/bloc/folders_bloc.dart'
    as _i6;
import 'package:cherry_note/features/folders/presentation/bloc/folders_event.dart'
    as _i8;
import 'package:cherry_note/features/folders/presentation/bloc/folders_state.dart'
    as _i2;
import 'package:cherry_note/features/notes/presentation/bloc/notes_bloc.dart'
    as _i10;
import 'package:cherry_note/features/notes/presentation/bloc/notes_event.dart'
    as _i11;
import 'package:cherry_note/features/notes/presentation/bloc/notes_state.dart'
    as _i3;
import 'package:cherry_note/features/tags/domain/entities/tag_filter.dart'
    as _i4;
import 'package:cherry_note/features/tags/presentation/bloc/tags_bloc.dart'
    as _i12;
import 'package:cherry_note/features/tags/presentation/bloc/tags_event.dart'
    as _i13;
import 'package:cherry_note/features/tags/presentation/bloc/tags_state.dart'
    as _i5;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoldersState_0 extends _i1.SmartFake implements _i2.FoldersState {
  _FakeFoldersState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotesState_1 extends _i1.SmartFake implements _i3.NotesState {
  _FakeNotesState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTagFilter_2 extends _i1.SmartFake implements _i4.TagFilter {
  _FakeTagFilter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTagsState_3 extends _i1.SmartFake implements _i5.TagsState {
  _FakeTagsState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FoldersBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoldersBloc extends _i1.Mock implements _i6.FoldersBloc {
  MockFoldersBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get expandedFolders => (super.noSuchMethod(
        Invocation.getter(#expandedFolders),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  _i2.FoldersState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFoldersState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.FoldersState);

  @override
  _i7.Stream<_i2.FoldersState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i2.FoldersState>.empty(),
      ) as _i7.Stream<_i2.FoldersState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool isFolderExpanded(String? folderPath) => (super.noSuchMethod(
        Invocation.method(
          #isFolderExpanded,
          [folderPath],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isFolderSelected(String? folderPath) => (super.noSuchMethod(
        Invocation.method(
          #isFolderSelected,
          [folderPath],
        ),
        returnValue: false,
      ) as bool);

  @override
  void add(_i8.FoldersEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i8.FoldersEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.FoldersState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i8.FoldersEvent>(
    _i9.EventHandler<E, _i2.FoldersState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i9.Transition<_i8.FoldersEvent, _i2.FoldersState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i2.FoldersState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NotesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesBloc extends _i1.Mock implements _i10.NotesBloc {
  MockNotesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NotesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNotesState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.NotesState);

  @override
  _i7.Stream<_i3.NotesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i3.NotesState>.empty(),
      ) as _i7.Stream<_i3.NotesState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i11.NotesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i11.NotesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.NotesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i11.NotesEvent>(
    _i9.EventHandler<E, _i3.NotesState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i9.Transition<_i11.NotesEvent, _i3.NotesState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i3.NotesState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TagsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagsBloc extends _i1.Mock implements _i12.TagsBloc {
  MockTagsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TagFilter get currentFilter => (super.noSuchMethod(
        Invocation.getter(#currentFilter),
        returnValue: _FakeTagFilter_2(
          this,
          Invocation.getter(#currentFilter),
        ),
      ) as _i4.TagFilter);

  @override
  int get selectedTagCount => (super.noSuchMethod(
        Invocation.getter(#selectedTagCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasActiveFilter => (super.noSuchMethod(
        Invocation.getter(#hasActiveFilter),
        returnValue: false,
      ) as bool);

  @override
  _i5.TagsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTagsState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.TagsState);

  @override
  _i7.Stream<_i5.TagsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i5.TagsState>.empty(),
      ) as _i7.Stream<_i5.TagsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool isTagSelectedForFilter(String? tagName) => (super.noSuchMethod(
        Invocation.method(
          #isTagSelectedForFilter,
          [tagName],
        ),
        returnValue: false,
      ) as bool);

  @override
  void add(_i13.TagsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i13.TagsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.TagsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i13.TagsEvent>(
    _i9.EventHandler<E, _i5.TagsState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i9.Transition<_i13.TagsEvent, _i5.TagsState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void onChange(_i9.Change<_i5.TagsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
