// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_note/test/features/folders/presentation/bloc/folders_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cherry_note/features/folders/domain/entities/folder_node.dart'
    as _i2;
import 'package:cherry_note/features/folders/domain/repositories/folder_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFolderNode_0 extends _i1.SmartFake implements _i2.FolderNode {
  _FakeFolderNode_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFolderStats_1 extends _i1.SmartFake implements _i2.FolderStats {
  _FakeFolderStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FolderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderRepository extends _i1.Mock implements _i3.FolderRepository {
  MockFolderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.FolderNode>> loadFolders({String? rootPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFolders,
          [],
          {#rootPath: rootPath},
        ),
        returnValue: _i4.Future<List<_i2.FolderNode>>.value(<_i2.FolderNode>[]),
      ) as _i4.Future<List<_i2.FolderNode>>);

  @override
  _i4.Future<_i2.FolderNode> createFolder({
    required String? parentPath,
    required String? folderName,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [],
          {
            #parentPath: parentPath,
            #folderName: folderName,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<_i2.FolderNode>.value(_FakeFolderNode_0(
          this,
          Invocation.method(
            #createFolder,
            [],
            {
              #parentPath: parentPath,
              #folderName: folderName,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i4.Future<_i2.FolderNode>);

  @override
  _i4.Future<_i2.FolderNode?> getFolder(String? folderPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolder,
          [folderPath],
        ),
        returnValue: _i4.Future<_i2.FolderNode?>.value(),
      ) as _i4.Future<_i2.FolderNode?>);

  @override
  _i4.Future<_i2.FolderNode> updateFolder(_i2.FolderNode? folder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFolder,
          [folder],
        ),
        returnValue: _i4.Future<_i2.FolderNode>.value(_FakeFolderNode_0(
          this,
          Invocation.method(
            #updateFolder,
            [folder],
          ),
        )),
      ) as _i4.Future<_i2.FolderNode>);

  @override
  _i4.Future<void> deleteFolder(
    String? folderPath, {
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [folderPath],
          {#recursive: recursive},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FolderNode> renameFolder(
    String? folderPath,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [
            folderPath,
            newName,
          ],
        ),
        returnValue: _i4.Future<_i2.FolderNode>.value(_FakeFolderNode_0(
          this,
          Invocation.method(
            #renameFolder,
            [
              folderPath,
              newName,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FolderNode>);

  @override
  _i4.Future<_i2.FolderNode> moveFolder(
    String? folderPath,
    String? newParentPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFolder,
          [
            folderPath,
            newParentPath,
          ],
        ),
        returnValue: _i4.Future<_i2.FolderNode>.value(_FakeFolderNode_0(
          this,
          Invocation.method(
            #moveFolder,
            [
              folderPath,
              newParentPath,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FolderNode>);

  @override
  _i4.Future<_i2.FolderNode> copyFolder(
    String? folderPath,
    String? newParentPath, {
    String? newName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyFolder,
          [
            folderPath,
            newParentPath,
          ],
          {#newName: newName},
        ),
        returnValue: _i4.Future<_i2.FolderNode>.value(_FakeFolderNode_0(
          this,
          Invocation.method(
            #copyFolder,
            [
              folderPath,
              newParentPath,
            ],
            {#newName: newName},
          ),
        )),
      ) as _i4.Future<_i2.FolderNode>);

  @override
  _i4.Future<List<_i2.FolderNode>> searchFolders({
    required String? query,
    String? rootPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFolders,
          [],
          {
            #query: query,
            #rootPath: rootPath,
          },
        ),
        returnValue: _i4.Future<List<_i2.FolderNode>>.value(<_i2.FolderNode>[]),
      ) as _i4.Future<List<_i2.FolderNode>>);

  @override
  _i4.Future<bool> folderExists(String? folderPath) => (super.noSuchMethod(
        Invocation.method(
          #folderExists,
          [folderPath],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.FolderStats> getFolderStats(String? folderPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderStats,
          [folderPath],
        ),
        returnValue: _i4.Future<_i2.FolderStats>.value(_FakeFolderStats_1(
          this,
          Invocation.method(
            #getFolderStats,
            [folderPath],
          ),
        )),
      ) as _i4.Future<_i2.FolderStats>);

  @override
  _i4.Future<Map<String, bool>> deleteFolders(
    List<String>? folderPaths, {
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolders,
          [folderPaths],
          {#recursive: recursive},
        ),
        returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i4.Future<Map<String, bool>>);

  @override
  _i4.Future<Map<String, bool>> moveFolders(
    List<String>? folderPaths,
    String? newParentPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFolders,
          [
            folderPaths,
            newParentPath,
          ],
        ),
        returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i4.Future<Map<String, bool>>);

  @override
  _i4.Future<Map<String, bool>> copyFolders(
    List<String>? folderPaths,
    String? newParentPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyFolders,
          [
            folderPaths,
            newParentPath,
          ],
        ),
        returnValue: _i4.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i4.Future<Map<String, bool>>);

  @override
  _i4.Future<List<String>> getFolderPaths({String? rootPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFolderPaths,
          [],
          {#rootPath: rootPath},
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  bool isValidFolderName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #isValidFolderName,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isValidFolderPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isValidFolderPath,
          [path],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<String> generateUniqueFolderName(
    String? parentPath,
    String? baseName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateUniqueFolderName,
          [
            parentPath,
            baseName,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #generateUniqueFolderName,
            [
              parentPath,
              baseName,
            ],
          ),
        )),
      ) as _i4.Future<String>);
}
